/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FreeStudyMaterialRouteImport } from './routes/free-study-material'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as CurrentAffairsRouteImport } from './routes/current-affairs'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatchesSlugRouteImport } from './routes/batches.$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMockTestsRouteImport } from './routes/_authenticated/mock-tests'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedMyBatchSlugRouteImport } from './routes/_authenticated/my-batch.$slug'
import { Route as AuthenticatedCbtTestIdRouteImport } from './routes/_authenticated/cbt.$testId'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedAdminResultsRouteImport } from './routes/_authenticated/admin.results'
import { Route as AuthenticatedAdminPdfsRouteImport } from './routes/_authenticated/admin.pdfs'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminLiveClassesRouteImport } from './routes/_authenticated/admin.live-classes'
import { Route as AuthenticatedAdminLiveChatRouteImport } from './routes/_authenticated/admin.live-chat'
import { Route as AuthenticatedAdminLecturesRouteImport } from './routes/_authenticated/admin.lectures'
import { Route as AuthenticatedAdminHeroSlidesRouteImport } from './routes/_authenticated/admin.hero-slides'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin.gallery'
import { Route as AuthenticatedAdminFacultyRouteImport } from './routes/_authenticated/admin.faculty'
import { Route as AuthenticatedAdminEnrollmentsRouteImport } from './routes/_authenticated/admin.enrollments'
import { Route as AuthenticatedAdminDppsRouteImport } from './routes/_authenticated/admin.dpps'
import { Route as AuthenticatedAdminCurrentAffairsRouteImport } from './routes/_authenticated/admin.current-affairs'
import { Route as AuthenticatedAdminCbtRouteImport } from './routes/_authenticated/admin.cbt'
import { Route as AuthenticatedAdminBatchesRouteImport } from './routes/_authenticated/admin.batches'
import { Route as AuthenticatedAdminCbtIndexRouteImport } from './routes/_authenticated/admin.cbt.index'
import { Route as AuthenticatedAdminBatchesIndexRouteImport } from './routes/_authenticated/admin.batches.index'
import { Route as AuthenticatedCbtTestIdResultRouteImport } from './routes/_authenticated/cbt.$testId.result'
import { Route as AuthenticatedCbtTestIdMistakesRouteImport } from './routes/_authenticated/cbt.$testId.mistakes'
import { Route as AuthenticatedCbtTestIdLeaderboardRouteImport } from './routes/_authenticated/cbt.$testId.leaderboard'
import { Route as AuthenticatedAdminBatchesBatchIdRouteImport } from './routes/_authenticated/admin.batches.$batchId'
import { Route as AuthenticatedAdminCbtTestIdQuestionsRouteImport } from './routes/_authenticated/admin.cbt.$testId.questions'
import { Route as AuthenticatedAdminCbtTestIdLeaderboardRouteImport } from './routes/_authenticated/admin.cbt.$testId.leaderboard'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeStudyMaterialRoute = FreeStudyMaterialRouteImport.update({
  id: '/free-study-material',
  path: '/free-study-material',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentAffairsRoute = CurrentAffairsRouteImport.update({
  id: '/current-affairs',
  path: '/current-affairs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesSlugRoute = BatchesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BatchesRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMockTestsRoute = AuthenticatedMockTestsRouteImport.update({
  id: '/mock-tests',
  path: '/mock-tests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedMyBatchSlugRoute =
  AuthenticatedMyBatchSlugRouteImport.update({
    id: '/my-batch/$slug',
    path: '/my-batch/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCbtTestIdRoute = AuthenticatedCbtTestIdRouteImport.update({
  id: '/cbt/$testId',
  path: '/cbt/$testId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResultsRoute =
  AuthenticatedAdminResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPdfsRoute = AuthenticatedAdminPdfsRouteImport.update({
  id: '/pdfs',
  path: '/pdfs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLiveClassesRoute =
  AuthenticatedAdminLiveClassesRouteImport.update({
    id: '/live-classes',
    path: '/live-classes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLiveChatRoute =
  AuthenticatedAdminLiveChatRouteImport.update({
    id: '/live-chat',
    path: '/live-chat',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLecturesRoute =
  AuthenticatedAdminLecturesRouteImport.update({
    id: '/lectures',
    path: '/lectures',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHeroSlidesRoute =
  AuthenticatedAdminHeroSlidesRouteImport.update({
    id: '/hero-slides',
    path: '/hero-slides',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFacultyRoute =
  AuthenticatedAdminFacultyRouteImport.update({
    id: '/faculty',
    path: '/faculty',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnrollmentsRoute =
  AuthenticatedAdminEnrollmentsRouteImport.update({
    id: '/enrollments',
    path: '/enrollments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDppsRoute = AuthenticatedAdminDppsRouteImport.update({
  id: '/dpps',
  path: '/dpps',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCurrentAffairsRoute =
  AuthenticatedAdminCurrentAffairsRouteImport.update({
    id: '/current-affairs',
    path: '/current-affairs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCbtRoute = AuthenticatedAdminCbtRouteImport.update({
  id: '/cbt',
  path: '/cbt',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBatchesRoute =
  AuthenticatedAdminBatchesRouteImport.update({
    id: '/batches',
    path: '/batches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCbtIndexRoute =
  AuthenticatedAdminCbtIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminCbtRoute,
  } as any)
const AuthenticatedAdminBatchesIndexRoute =
  AuthenticatedAdminBatchesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminBatchesRoute,
  } as any)
const AuthenticatedCbtTestIdResultRoute =
  AuthenticatedCbtTestIdResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => AuthenticatedCbtTestIdRoute,
  } as any)
const AuthenticatedCbtTestIdMistakesRoute =
  AuthenticatedCbtTestIdMistakesRouteImport.update({
    id: '/mistakes',
    path: '/mistakes',
    getParentRoute: () => AuthenticatedCbtTestIdRoute,
  } as any)
const AuthenticatedCbtTestIdLeaderboardRoute =
  AuthenticatedCbtTestIdLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedCbtTestIdRoute,
  } as any)
const AuthenticatedAdminBatchesBatchIdRoute =
  AuthenticatedAdminBatchesBatchIdRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => AuthenticatedAdminBatchesRoute,
  } as any)
const AuthenticatedAdminCbtTestIdQuestionsRoute =
  AuthenticatedAdminCbtTestIdQuestionsRouteImport.update({
    id: '/$testId/questions',
    path: '/$testId/questions',
    getParentRoute: () => AuthenticatedAdminCbtRoute,
  } as any)
const AuthenticatedAdminCbtTestIdLeaderboardRoute =
  AuthenticatedAdminCbtTestIdLeaderboardRouteImport.update({
    id: '/$testId/leaderboard',
    path: '/$testId/leaderboard',
    getParentRoute: () => AuthenticatedAdminCbtRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/batches': typeof BatchesRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/faculty': typeof FacultyRoute
  '/free-study-material': typeof FreeStudyMaterialRoute
  '/gallery': typeof GalleryRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mock-tests': typeof AuthenticatedMockTestsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/batches/$slug': typeof BatchesSlugRoute
  '/admin/batches': typeof AuthenticatedAdminBatchesRouteWithChildren
  '/admin/cbt': typeof AuthenticatedAdminCbtRouteWithChildren
  '/admin/current-affairs': typeof AuthenticatedAdminCurrentAffairsRoute
  '/admin/dpps': typeof AuthenticatedAdminDppsRoute
  '/admin/enrollments': typeof AuthenticatedAdminEnrollmentsRoute
  '/admin/faculty': typeof AuthenticatedAdminFacultyRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/hero-slides': typeof AuthenticatedAdminHeroSlidesRoute
  '/admin/lectures': typeof AuthenticatedAdminLecturesRoute
  '/admin/live-chat': typeof AuthenticatedAdminLiveChatRoute
  '/admin/live-classes': typeof AuthenticatedAdminLiveClassesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/pdfs': typeof AuthenticatedAdminPdfsRoute
  '/admin/results': typeof AuthenticatedAdminResultsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/cbt/$testId': typeof AuthenticatedCbtTestIdRouteWithChildren
  '/my-batch/$slug': typeof AuthenticatedMyBatchSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/batches/$batchId': typeof AuthenticatedAdminBatchesBatchIdRoute
  '/cbt/$testId/leaderboard': typeof AuthenticatedCbtTestIdLeaderboardRoute
  '/cbt/$testId/mistakes': typeof AuthenticatedCbtTestIdMistakesRoute
  '/cbt/$testId/result': typeof AuthenticatedCbtTestIdResultRoute
  '/admin/batches/': typeof AuthenticatedAdminBatchesIndexRoute
  '/admin/cbt/': typeof AuthenticatedAdminCbtIndexRoute
  '/admin/cbt/$testId/leaderboard': typeof AuthenticatedAdminCbtTestIdLeaderboardRoute
  '/admin/cbt/$testId/questions': typeof AuthenticatedAdminCbtTestIdQuestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/batches': typeof BatchesRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/faculty': typeof FacultyRoute
  '/free-study-material': typeof FreeStudyMaterialRoute
  '/gallery': typeof GalleryRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mock-tests': typeof AuthenticatedMockTestsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/batches/$slug': typeof BatchesSlugRoute
  '/admin/current-affairs': typeof AuthenticatedAdminCurrentAffairsRoute
  '/admin/dpps': typeof AuthenticatedAdminDppsRoute
  '/admin/enrollments': typeof AuthenticatedAdminEnrollmentsRoute
  '/admin/faculty': typeof AuthenticatedAdminFacultyRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/hero-slides': typeof AuthenticatedAdminHeroSlidesRoute
  '/admin/lectures': typeof AuthenticatedAdminLecturesRoute
  '/admin/live-chat': typeof AuthenticatedAdminLiveChatRoute
  '/admin/live-classes': typeof AuthenticatedAdminLiveClassesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/pdfs': typeof AuthenticatedAdminPdfsRoute
  '/admin/results': typeof AuthenticatedAdminResultsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/cbt/$testId': typeof AuthenticatedCbtTestIdRouteWithChildren
  '/my-batch/$slug': typeof AuthenticatedMyBatchSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/batches/$batchId': typeof AuthenticatedAdminBatchesBatchIdRoute
  '/cbt/$testId/leaderboard': typeof AuthenticatedCbtTestIdLeaderboardRoute
  '/cbt/$testId/mistakes': typeof AuthenticatedCbtTestIdMistakesRoute
  '/cbt/$testId/result': typeof AuthenticatedCbtTestIdResultRoute
  '/admin/batches': typeof AuthenticatedAdminBatchesIndexRoute
  '/admin/cbt': typeof AuthenticatedAdminCbtIndexRoute
  '/admin/cbt/$testId/leaderboard': typeof AuthenticatedAdminCbtTestIdLeaderboardRoute
  '/admin/cbt/$testId/questions': typeof AuthenticatedAdminCbtTestIdQuestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/batches': typeof BatchesRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/faculty': typeof FacultyRoute
  '/free-study-material': typeof FreeStudyMaterialRoute
  '/gallery': typeof GalleryRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mock-tests': typeof AuthenticatedMockTestsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/batches/$slug': typeof BatchesSlugRoute
  '/_authenticated/admin/batches': typeof AuthenticatedAdminBatchesRouteWithChildren
  '/_authenticated/admin/cbt': typeof AuthenticatedAdminCbtRouteWithChildren
  '/_authenticated/admin/current-affairs': typeof AuthenticatedAdminCurrentAffairsRoute
  '/_authenticated/admin/dpps': typeof AuthenticatedAdminDppsRoute
  '/_authenticated/admin/enrollments': typeof AuthenticatedAdminEnrollmentsRoute
  '/_authenticated/admin/faculty': typeof AuthenticatedAdminFacultyRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/hero-slides': typeof AuthenticatedAdminHeroSlidesRoute
  '/_authenticated/admin/lectures': typeof AuthenticatedAdminLecturesRoute
  '/_authenticated/admin/live-chat': typeof AuthenticatedAdminLiveChatRoute
  '/_authenticated/admin/live-classes': typeof AuthenticatedAdminLiveClassesRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/pdfs': typeof AuthenticatedAdminPdfsRoute
  '/_authenticated/admin/results': typeof AuthenticatedAdminResultsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/cbt/$testId': typeof AuthenticatedCbtTestIdRouteWithChildren
  '/_authenticated/my-batch/$slug': typeof AuthenticatedMyBatchSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/batches/$batchId': typeof AuthenticatedAdminBatchesBatchIdRoute
  '/_authenticated/cbt/$testId/leaderboard': typeof AuthenticatedCbtTestIdLeaderboardRoute
  '/_authenticated/cbt/$testId/mistakes': typeof AuthenticatedCbtTestIdMistakesRoute
  '/_authenticated/cbt/$testId/result': typeof AuthenticatedCbtTestIdResultRoute
  '/_authenticated/admin/batches/': typeof AuthenticatedAdminBatchesIndexRoute
  '/_authenticated/admin/cbt/': typeof AuthenticatedAdminCbtIndexRoute
  '/_authenticated/admin/cbt/$testId/leaderboard': typeof AuthenticatedAdminCbtTestIdLeaderboardRoute
  '/_authenticated/admin/cbt/$testId/questions': typeof AuthenticatedAdminCbtTestIdQuestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/batches'
    | '/contact'
    | '/courses'
    | '/current-affairs'
    | '/faculty'
    | '/free-study-material'
    | '/gallery'
    | '/notifications'
    | '/reset-password'
    | '/results'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/mock-tests'
    | '/profile'
    | '/batches/$slug'
    | '/admin/batches'
    | '/admin/cbt'
    | '/admin/current-affairs'
    | '/admin/dpps'
    | '/admin/enrollments'
    | '/admin/faculty'
    | '/admin/gallery'
    | '/admin/hero-slides'
    | '/admin/lectures'
    | '/admin/live-chat'
    | '/admin/live-classes'
    | '/admin/notifications'
    | '/admin/pdfs'
    | '/admin/results'
    | '/admin/students'
    | '/cbt/$testId'
    | '/my-batch/$slug'
    | '/admin/'
    | '/admin/batches/$batchId'
    | '/cbt/$testId/leaderboard'
    | '/cbt/$testId/mistakes'
    | '/cbt/$testId/result'
    | '/admin/batches/'
    | '/admin/cbt/'
    | '/admin/cbt/$testId/leaderboard'
    | '/admin/cbt/$testId/questions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/batches'
    | '/contact'
    | '/courses'
    | '/current-affairs'
    | '/faculty'
    | '/free-study-material'
    | '/gallery'
    | '/notifications'
    | '/reset-password'
    | '/results'
    | '/sitemap.xml'
    | '/dashboard'
    | '/mock-tests'
    | '/profile'
    | '/batches/$slug'
    | '/admin/current-affairs'
    | '/admin/dpps'
    | '/admin/enrollments'
    | '/admin/faculty'
    | '/admin/gallery'
    | '/admin/hero-slides'
    | '/admin/lectures'
    | '/admin/live-chat'
    | '/admin/live-classes'
    | '/admin/notifications'
    | '/admin/pdfs'
    | '/admin/results'
    | '/admin/students'
    | '/cbt/$testId'
    | '/my-batch/$slug'
    | '/admin'
    | '/admin/batches/$batchId'
    | '/cbt/$testId/leaderboard'
    | '/cbt/$testId/mistakes'
    | '/cbt/$testId/result'
    | '/admin/batches'
    | '/admin/cbt'
    | '/admin/cbt/$testId/leaderboard'
    | '/admin/cbt/$testId/questions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/batches'
    | '/contact'
    | '/courses'
    | '/current-affairs'
    | '/faculty'
    | '/free-study-material'
    | '/gallery'
    | '/notifications'
    | '/reset-password'
    | '/results'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/mock-tests'
    | '/_authenticated/profile'
    | '/batches/$slug'
    | '/_authenticated/admin/batches'
    | '/_authenticated/admin/cbt'
    | '/_authenticated/admin/current-affairs'
    | '/_authenticated/admin/dpps'
    | '/_authenticated/admin/enrollments'
    | '/_authenticated/admin/faculty'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/hero-slides'
    | '/_authenticated/admin/lectures'
    | '/_authenticated/admin/live-chat'
    | '/_authenticated/admin/live-classes'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/pdfs'
    | '/_authenticated/admin/results'
    | '/_authenticated/admin/students'
    | '/_authenticated/cbt/$testId'
    | '/_authenticated/my-batch/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/batches/$batchId'
    | '/_authenticated/cbt/$testId/leaderboard'
    | '/_authenticated/cbt/$testId/mistakes'
    | '/_authenticated/cbt/$testId/result'
    | '/_authenticated/admin/batches/'
    | '/_authenticated/admin/cbt/'
    | '/_authenticated/admin/cbt/$testId/leaderboard'
    | '/_authenticated/admin/cbt/$testId/questions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BatchesRoute: typeof BatchesRouteWithChildren
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  CurrentAffairsRoute: typeof CurrentAffairsRoute
  FacultyRoute: typeof FacultyRoute
  FreeStudyMaterialRoute: typeof FreeStudyMaterialRoute
  GalleryRoute: typeof GalleryRoute
  NotificationsRoute: typeof NotificationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResultsRoute: typeof ResultsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-study-material': {
      id: '/free-study-material'
      path: '/free-study-material'
      fullPath: '/free-study-material'
      preLoaderRoute: typeof FreeStudyMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-affairs': {
      id: '/current-affairs'
      path: '/current-affairs'
      fullPath: '/current-affairs'
      preLoaderRoute: typeof CurrentAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$slug': {
      id: '/batches/$slug'
      path: '/$slug'
      fullPath: '/batches/$slug'
      preLoaderRoute: typeof BatchesSlugRouteImport
      parentRoute: typeof BatchesRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mock-tests': {
      id: '/_authenticated/mock-tests'
      path: '/mock-tests'
      fullPath: '/mock-tests'
      preLoaderRoute: typeof AuthenticatedMockTestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/my-batch/$slug': {
      id: '/_authenticated/my-batch/$slug'
      path: '/my-batch/$slug'
      fullPath: '/my-batch/$slug'
      preLoaderRoute: typeof AuthenticatedMyBatchSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cbt/$testId': {
      id: '/_authenticated/cbt/$testId'
      path: '/cbt/$testId'
      fullPath: '/cbt/$testId'
      preLoaderRoute: typeof AuthenticatedCbtTestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/results': {
      id: '/_authenticated/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AuthenticatedAdminResultsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pdfs': {
      id: '/_authenticated/admin/pdfs'
      path: '/pdfs'
      fullPath: '/admin/pdfs'
      preLoaderRoute: typeof AuthenticatedAdminPdfsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/live-classes': {
      id: '/_authenticated/admin/live-classes'
      path: '/live-classes'
      fullPath: '/admin/live-classes'
      preLoaderRoute: typeof AuthenticatedAdminLiveClassesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/live-chat': {
      id: '/_authenticated/admin/live-chat'
      path: '/live-chat'
      fullPath: '/admin/live-chat'
      preLoaderRoute: typeof AuthenticatedAdminLiveChatRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lectures': {
      id: '/_authenticated/admin/lectures'
      path: '/lectures'
      fullPath: '/admin/lectures'
      preLoaderRoute: typeof AuthenticatedAdminLecturesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hero-slides': {
      id: '/_authenticated/admin/hero-slides'
      path: '/hero-slides'
      fullPath: '/admin/hero-slides'
      preLoaderRoute: typeof AuthenticatedAdminHeroSlidesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/faculty': {
      id: '/_authenticated/admin/faculty'
      path: '/faculty'
      fullPath: '/admin/faculty'
      preLoaderRoute: typeof AuthenticatedAdminFacultyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enrollments': {
      id: '/_authenticated/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AuthenticatedAdminEnrollmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dpps': {
      id: '/_authenticated/admin/dpps'
      path: '/dpps'
      fullPath: '/admin/dpps'
      preLoaderRoute: typeof AuthenticatedAdminDppsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/current-affairs': {
      id: '/_authenticated/admin/current-affairs'
      path: '/current-affairs'
      fullPath: '/admin/current-affairs'
      preLoaderRoute: typeof AuthenticatedAdminCurrentAffairsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cbt': {
      id: '/_authenticated/admin/cbt'
      path: '/cbt'
      fullPath: '/admin/cbt'
      preLoaderRoute: typeof AuthenticatedAdminCbtRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/batches': {
      id: '/_authenticated/admin/batches'
      path: '/batches'
      fullPath: '/admin/batches'
      preLoaderRoute: typeof AuthenticatedAdminBatchesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cbt/': {
      id: '/_authenticated/admin/cbt/'
      path: '/'
      fullPath: '/admin/cbt/'
      preLoaderRoute: typeof AuthenticatedAdminCbtIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCbtRoute
    }
    '/_authenticated/admin/batches/': {
      id: '/_authenticated/admin/batches/'
      path: '/'
      fullPath: '/admin/batches/'
      preLoaderRoute: typeof AuthenticatedAdminBatchesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminBatchesRoute
    }
    '/_authenticated/cbt/$testId/result': {
      id: '/_authenticated/cbt/$testId/result'
      path: '/result'
      fullPath: '/cbt/$testId/result'
      preLoaderRoute: typeof AuthenticatedCbtTestIdResultRouteImport
      parentRoute: typeof AuthenticatedCbtTestIdRoute
    }
    '/_authenticated/cbt/$testId/mistakes': {
      id: '/_authenticated/cbt/$testId/mistakes'
      path: '/mistakes'
      fullPath: '/cbt/$testId/mistakes'
      preLoaderRoute: typeof AuthenticatedCbtTestIdMistakesRouteImport
      parentRoute: typeof AuthenticatedCbtTestIdRoute
    }
    '/_authenticated/cbt/$testId/leaderboard': {
      id: '/_authenticated/cbt/$testId/leaderboard'
      path: '/leaderboard'
      fullPath: '/cbt/$testId/leaderboard'
      preLoaderRoute: typeof AuthenticatedCbtTestIdLeaderboardRouteImport
      parentRoute: typeof AuthenticatedCbtTestIdRoute
    }
    '/_authenticated/admin/batches/$batchId': {
      id: '/_authenticated/admin/batches/$batchId'
      path: '/$batchId'
      fullPath: '/admin/batches/$batchId'
      preLoaderRoute: typeof AuthenticatedAdminBatchesBatchIdRouteImport
      parentRoute: typeof AuthenticatedAdminBatchesRoute
    }
    '/_authenticated/admin/cbt/$testId/questions': {
      id: '/_authenticated/admin/cbt/$testId/questions'
      path: '/$testId/questions'
      fullPath: '/admin/cbt/$testId/questions'
      preLoaderRoute: typeof AuthenticatedAdminCbtTestIdQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminCbtRoute
    }
    '/_authenticated/admin/cbt/$testId/leaderboard': {
      id: '/_authenticated/admin/cbt/$testId/leaderboard'
      path: '/$testId/leaderboard'
      fullPath: '/admin/cbt/$testId/leaderboard'
      preLoaderRoute: typeof AuthenticatedAdminCbtTestIdLeaderboardRouteImport
      parentRoute: typeof AuthenticatedAdminCbtRoute
    }
  }
}

interface AuthenticatedAdminBatchesRouteChildren {
  AuthenticatedAdminBatchesBatchIdRoute: typeof AuthenticatedAdminBatchesBatchIdRoute
  AuthenticatedAdminBatchesIndexRoute: typeof AuthenticatedAdminBatchesIndexRoute
}

const AuthenticatedAdminBatchesRouteChildren: AuthenticatedAdminBatchesRouteChildren =
  {
    AuthenticatedAdminBatchesBatchIdRoute:
      AuthenticatedAdminBatchesBatchIdRoute,
    AuthenticatedAdminBatchesIndexRoute: AuthenticatedAdminBatchesIndexRoute,
  }

const AuthenticatedAdminBatchesRouteWithChildren =
  AuthenticatedAdminBatchesRoute._addFileChildren(
    AuthenticatedAdminBatchesRouteChildren,
  )

interface AuthenticatedAdminCbtRouteChildren {
  AuthenticatedAdminCbtIndexRoute: typeof AuthenticatedAdminCbtIndexRoute
  AuthenticatedAdminCbtTestIdLeaderboardRoute: typeof AuthenticatedAdminCbtTestIdLeaderboardRoute
  AuthenticatedAdminCbtTestIdQuestionsRoute: typeof AuthenticatedAdminCbtTestIdQuestionsRoute
}

const AuthenticatedAdminCbtRouteChildren: AuthenticatedAdminCbtRouteChildren = {
  AuthenticatedAdminCbtIndexRoute: AuthenticatedAdminCbtIndexRoute,
  AuthenticatedAdminCbtTestIdLeaderboardRoute:
    AuthenticatedAdminCbtTestIdLeaderboardRoute,
  AuthenticatedAdminCbtTestIdQuestionsRoute:
    AuthenticatedAdminCbtTestIdQuestionsRoute,
}

const AuthenticatedAdminCbtRouteWithChildren =
  AuthenticatedAdminCbtRoute._addFileChildren(
    AuthenticatedAdminCbtRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBatchesRoute: typeof AuthenticatedAdminBatchesRouteWithChildren
  AuthenticatedAdminCbtRoute: typeof AuthenticatedAdminCbtRouteWithChildren
  AuthenticatedAdminCurrentAffairsRoute: typeof AuthenticatedAdminCurrentAffairsRoute
  AuthenticatedAdminDppsRoute: typeof AuthenticatedAdminDppsRoute
  AuthenticatedAdminEnrollmentsRoute: typeof AuthenticatedAdminEnrollmentsRoute
  AuthenticatedAdminFacultyRoute: typeof AuthenticatedAdminFacultyRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminHeroSlidesRoute: typeof AuthenticatedAdminHeroSlidesRoute
  AuthenticatedAdminLecturesRoute: typeof AuthenticatedAdminLecturesRoute
  AuthenticatedAdminLiveChatRoute: typeof AuthenticatedAdminLiveChatRoute
  AuthenticatedAdminLiveClassesRoute: typeof AuthenticatedAdminLiveClassesRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPdfsRoute: typeof AuthenticatedAdminPdfsRoute
  AuthenticatedAdminResultsRoute: typeof AuthenticatedAdminResultsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBatchesRoute: AuthenticatedAdminBatchesRouteWithChildren,
  AuthenticatedAdminCbtRoute: AuthenticatedAdminCbtRouteWithChildren,
  AuthenticatedAdminCurrentAffairsRoute: AuthenticatedAdminCurrentAffairsRoute,
  AuthenticatedAdminDppsRoute: AuthenticatedAdminDppsRoute,
  AuthenticatedAdminEnrollmentsRoute: AuthenticatedAdminEnrollmentsRoute,
  AuthenticatedAdminFacultyRoute: AuthenticatedAdminFacultyRoute,
  AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
  AuthenticatedAdminHeroSlidesRoute: AuthenticatedAdminHeroSlidesRoute,
  AuthenticatedAdminLecturesRoute: AuthenticatedAdminLecturesRoute,
  AuthenticatedAdminLiveChatRoute: AuthenticatedAdminLiveChatRoute,
  AuthenticatedAdminLiveClassesRoute: AuthenticatedAdminLiveClassesRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPdfsRoute: AuthenticatedAdminPdfsRoute,
  AuthenticatedAdminResultsRoute: AuthenticatedAdminResultsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCbtTestIdRouteChildren {
  AuthenticatedCbtTestIdLeaderboardRoute: typeof AuthenticatedCbtTestIdLeaderboardRoute
  AuthenticatedCbtTestIdMistakesRoute: typeof AuthenticatedCbtTestIdMistakesRoute
  AuthenticatedCbtTestIdResultRoute: typeof AuthenticatedCbtTestIdResultRoute
}

const AuthenticatedCbtTestIdRouteChildren: AuthenticatedCbtTestIdRouteChildren =
  {
    AuthenticatedCbtTestIdLeaderboardRoute:
      AuthenticatedCbtTestIdLeaderboardRoute,
    AuthenticatedCbtTestIdMistakesRoute: AuthenticatedCbtTestIdMistakesRoute,
    AuthenticatedCbtTestIdResultRoute: AuthenticatedCbtTestIdResultRoute,
  }

const AuthenticatedCbtTestIdRouteWithChildren =
  AuthenticatedCbtTestIdRoute._addFileChildren(
    AuthenticatedCbtTestIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMockTestsRoute: typeof AuthenticatedMockTestsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedCbtTestIdRoute: typeof AuthenticatedCbtTestIdRouteWithChildren
  AuthenticatedMyBatchSlugRoute: typeof AuthenticatedMyBatchSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMockTestsRoute: AuthenticatedMockTestsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedCbtTestIdRoute: AuthenticatedCbtTestIdRouteWithChildren,
  AuthenticatedMyBatchSlugRoute: AuthenticatedMyBatchSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BatchesRouteChildren {
  BatchesSlugRoute: typeof BatchesSlugRoute
}

const BatchesRouteChildren: BatchesRouteChildren = {
  BatchesSlugRoute: BatchesSlugRoute,
}

const BatchesRouteWithChildren =
  BatchesRoute._addFileChildren(BatchesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BatchesRoute: BatchesRouteWithChildren,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  CurrentAffairsRoute: CurrentAffairsRoute,
  FacultyRoute: FacultyRoute,
  FreeStudyMaterialRoute: FreeStudyMaterialRoute,
  GalleryRoute: GalleryRoute,
  NotificationsRoute: NotificationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResultsRoute: ResultsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
